on:
  push:
    branches:
      - '**'

env:
  TF_IN_AUTOMATION: 1
  TF_INPUT: 0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Prepare Google application credentials"
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_CREDENTIALS }}" >> ${{ github.workspace }}/application-default-credentials.json
          echo "::set-env name=GOOGLE_APPLICATION_CREDENTIALS::${{ github.workspace }}/application-default-credentials.json"

      - name: "Deploy project"
        run: cd configurations/${{ github.repository }}/project && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply

      - name: "Deploy storage"
        run: cd configurations/${{ github.repository }}/storage && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply

      - name: "Deploy builders"
        run: (TF_VAR_github_pat=${{ secrets.GAME_GITHUB_PAT }}; cd configurations/${{ github.repository }}/builders && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply)
