on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Deploy project"
        run: (TF_IN_AUTOMATION=1; TF_INPUT=0; cd configurations/${{ github.repository }}/project && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply)

      - name: "Deploy storage"
        run: (TF_IN_AUTOMATION=1; TF_INPUT=0; cd configurations/${{ github.repository }}/storage && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply)

      - name: "Deploy builders"
        run: (TF_IN_AUTOMATION=1; TF_INPUT=0; TF_VAR_github_pat=${{ secrets.GAME_GITHUB_PAT }}; cd configurations/${{ github.repository }}/builders && terraform init -backend-config=../backend.hcl && terraform plan && terraform apply)
